apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim

# This spec basically means, telling Kubernetes to find the storage with below requirments for the pod
spec:
  accessModes:
    - ReadWriteOnce         # Can be used by a single node at a time
  resources:
    requests:
      storage: 2Gi          # 2GB of storage